name: Deployment Environment

on:
  workflow_dispatch

jobs:
  train-in-dev:
    runs-on: ubuntu-latest
    name: experiment
    environment: development
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Run training job
        run: >-
          az ml job create --file src/job.yml -w bobos-new-ws -g bobos-new-rg
          --set inputs.training_data.type=uri_folder
          --set inputs.training_data.path=${{ vars.TRAINING_DATA_PATH }}
          --stream
  train-in-prod:
    runs-on: ubuntu-latest
    name: production
    environment: production
    needs: train-in-dev
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_PROD}}
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Run training job
        run: >-
          az ml job create --file src/job.yml -w bobos-new-ws -g bobos-new-rg
          --set inputs.training_data.type=uri_folder
          --set inputs.training_data.path=${{ vars.TRAINING_DATA_PATH }}
