name: Deployment Environment

on:
  push:
    branches:
      - main

jobs:
  train-in-dev:
    runs-on: ubuntu-latest
    name: experiment
    environment: development
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Run training job
        run: >-
          az ml job create
          -w bobos-new-ws
          -g bobos-new-rg
          --file src/job.yml
          --name ifear${{ github.run_id }}
          --set inputs.training_data.type=uri_folder
          --set inputs.training_data.path=${{ vars.TRAINING_DATA_PATH }}
          --stream
      - name: Register model
        run: >-
          az ml model create
          -w bobos-new-ws
          -g bobos-new-rg
          --name maybefallinlove-model
          --path azureml://jobs/ifear${{ github.run_id }}/outputs/artifacts
          --type mlflow_model
      - name: Deploy model
        run: >-

  # train-in-prod:
  #   runs-on: ubuntu-latest
  #   name: production
  #   environment: production
  #   needs: train-in-dev
  #   steps:
  #     - name: Azure login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{secrets.AZURE_CREDENTIALS_PROD}}
  #     - name: Checkout repo
  #       uses: actions/checkout@main
  #     - name: Install az ml extension
  #       run: az extension add -n ml -y
  #     - name: Run training job
  #       run: >-
  #         az ml job create --file src/job.yml -w bobos-new-ws -g bobos-new-rg
  #         --set inputs.training_data.type=uri_folder
  #         --set inputs.training_data.path=${{ vars.TRAINING_DATA_PATH }}
