name: Deployment Environment

on:
  workflow_call:
    inputs:
      training_data_path:
        description: Path to the training data asset in Azure ML
        required: true
        type: string
      job_name:
        description: Job name
        required: true
        type: string
      environment:
        description: The Github env
        required: true
        type: string

jobs:
  train:
    runs-on: ubuntu-latest
    name: ${{ vars.job_name }}
    environment: development
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Run training job
        run: >-
          az ml job create --file src/job.yml -w bobos-new-ws -g bobos-new-rg
          --set inputs.training_data.type=uri_folder
          --set inputs.training_data.path=${{ vars.TRAINING_DATA_PATH }}
          --stream
