name: Deployment Environment

on:
  push:
    branches: main

jobs:
  login:
    name: login
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
