name: Deployment Environment

on: push

jobs:
  login:
    runs-on: ubuntu-latest
    name: login
    environment: development
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}
