name: Deployment Environment

environment:
  name: development

on: push

jobs:
  login:
    runs-on: ubuntu-latest
    name: login
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}
