name: Deployment Environment

on:
  push:
    # branches:
    #   - main

jobs:
  train-in-dev:
    uses: ./github/workflows/05-envs-base.yml
    with:
      training_data_path: azureml:diabetes-dev-folder@latest

  train-in-prod:
    needs: train-in-dev
    uses: ./github/workflows/05-envs-base.yml
    with:
      training_data_path: azureml:diabetes-prod-folder@latest